import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> datetime:
    return datetime.now(timezone.utc)


class Role(str, enum.Enum):
    conductor = "conductor"
    methodologist = "methodologist"


class Employee(Base):
    __tablename__ = "employees"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    full_name: Mapped[str] = mapped_column(String(200))
    depot: Mapped[str] = mapped_column(String(200), default="")
    brigade: Mapped[str] = mapped_column(String(200), default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    # Only fictional demo accounts have a login; the role is read from here, never from the request.
    login: Mapped[str | None] = mapped_column(String(50), unique=True, nullable=True)
    password_hash: Mapped[str | None] = mapped_column(String(200), nullable=True)
    role: Mapped[str] = mapped_column(String(20), default=Role.conductor.value, server_default="conductor")
    # Synthetic colleagues whose history was generated by the seed, shown as such in the UI.
    is_synthetic: Mapped[bool] = mapped_column(Boolean, default=False, server_default="0")

    attempts: Mapped[list["Attempt"]] = relationship(back_populates="employee")


class Scenario(Base):
    """Published fields (title..graph, version >= 1) plus an optional editor draft.

    version 0 means "never published": such scenarios are invisible to conductors.
    """

    __tablename__ = "scenarios"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    title: Mapped[str] = mapped_column(String(300))
    description: Mapped[str] = mapped_column(Text, default="")
    graph: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    # Catalog tags; competency ids among them drive recommendations.
    tags: Mapped[list] = mapped_column(JSON, default=list)
    version: Mapped[int] = mapped_column(Integer, default=1, server_default="1")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    # {"title", "description", "tags", "graph"} being edited; not validated until publishing.
    draft: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    # Stable key of a bundled scenario (file name) and who last published it: builtin | api | editor.
    key: Mapped[str | None] = mapped_column(String(100), unique=True, nullable=True)
    origin: Mapped[str] = mapped_column(String(20), default="api", server_default="api")
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    attempts: Mapped[list["Attempt"]] = relationship(back_populates="scenario")


class AttemptStatus(str, enum.Enum):
    in_progress = "in_progress"
    finished = "finished"


class Attempt(Base):
    __tablename__ = "attempts"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    employee_id: Mapped[str] = mapped_column(ForeignKey("employees.id"))
    scenario_id: Mapped[str] = mapped_column(ForeignKey("scenarios.id"))
    # Frozen copy of the graph at start: later edits to the scenario never affect this attempt.
    scenario_version: Mapped[int] = mapped_column(Integer, default=1, server_default="1")
    scenario_title: Mapped[str] = mapped_column(String(300), default="", server_default="")
    graph_snapshot: Mapped[dict] = mapped_column(JSON)

    current_node: Mapped[str] = mapped_column(String(100))
    step: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    loyalty: Mapped[int] = mapped_column(Integer, default=50)
    safety: Mapped[int] = mapped_column(Integer, default=50)
    flags: Mapped[dict] = mapped_column(JSON, default=dict)
    # Running competency totals {id: {"earned", "max"}}; see gamification/competencies.py.
    assessment: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    status: Mapped[AttemptStatus] = mapped_column(
        Enum(AttemptStatus, name="attempt_status"), default=AttemptStatus.in_progress
    )
    ending_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    node_shown_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # Filled once, in the same transaction as the finishing step (see services/rewards.py).
    score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    xp_gained: Mapped[int | None] = mapped_column(Integer, nullable=True)
    is_synthetic: Mapped[bool] = mapped_column(Boolean, default=False, server_default="0")

    employee: Mapped[Employee] = relationship(back_populates="attempts")
    scenario: Mapped[Scenario] = relationship(back_populates="attempts")
    logs: Mapped[list["ChoiceLog"]] = relationship(back_populates="attempt", order_by="ChoiceLog.step")


class ChoiceLog(Base):
    """One row per applied step; the unique (attempt_id, step) pair rejects a concurrent duplicate."""

    __tablename__ = "choice_logs"
    __table_args__ = (UniqueConstraint("attempt_id", "step", name="uq_choice_logs_attempt_step"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    attempt_id: Mapped[str] = mapped_column(ForeignKey("attempts.id"))
    step: Mapped[int] = mapped_column(Integer)
    node_id: Mapped[str] = mapped_column(String(100))
    choice_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    timed_out: Mapped[bool] = mapped_column(default=False)
    next_node: Mapped[str | None] = mapped_column(String(100), nullable=True)
    loyalty_delta: Mapped[int] = mapped_column(Integer, default=0)
    safety_delta: Mapped[int] = mapped_column(Integer, default=0)
    loyalty_after: Mapped[int | None] = mapped_column(Integer, nullable=True)
    safety_after: Mapped[int | None] = mapped_column(Integer, nullable=True)
    assessment: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    attempt: Mapped[Attempt] = relationship(back_populates="logs")


class AuthSession(Base):
    __tablename__ = "auth_sessions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    token_hash: Mapped[str] = mapped_column(String(64), unique=True)
    employee_id: Mapped[str] = mapped_column(ForeignKey("employees.id"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    employee: Mapped[Employee] = relationship()


class ScenarioBest(Base):
    """Best score per employee and scenario; XP is the sum of these, so replays cannot farm XP."""

    __tablename__ = "scenario_bests"
    __table_args__ = (UniqueConstraint("employee_id", "scenario_id", name="uq_scenario_bests_employee_scenario"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    employee_id: Mapped[str] = mapped_column(ForeignKey("employees.id"))
    scenario_id: Mapped[str] = mapped_column(ForeignKey("scenarios.id"))
    best_score: Mapped[int] = mapped_column(Integer)
    attempt_id: Mapped[str] = mapped_column(ForeignKey("attempts.id"))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)


class EmployeeAchievement(Base):
    __tablename__ = "employee_achievements"
    __table_args__ = (UniqueConstraint("employee_id", "achievement_id", name="uq_employee_achievements_once"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    employee_id: Mapped[str] = mapped_column(ForeignKey("employees.id"))
    achievement_id: Mapped[str] = mapped_column(String(50))
    attempt_id: Mapped[str | None] = mapped_column(ForeignKey("attempts.id"), nullable=True)
    awarded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)


class Notification(Base):
    __tablename__ = "notifications"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    employee_id: Mapped[str] = mapped_column(ForeignKey("employees.id"), index=True)
    kind: Mapped[str] = mapped_column(String(30))
    title: Mapped[str] = mapped_column(String(200))
    body: Mapped[str] = mapped_column(Text, default="")
    link: Mapped[str | None] = mapped_column(String(300), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
