"""Load built-in scenarios and fictional demo accounts.

Run after migrations: python -m app.db_upgrade && python -m app.seed
A scenario whose data changed is updated in place with version + 1; attempts
already started keep their own snapshot.
"""

from datetime import datetime, timedelta

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.core.clock import utcnow
from app.core.config import settings
from app.core.db import SessionLocal
from app.core.security import hash_password, verify_password
from app.models.models import Attempt, Employee, Role, Scenario
from app.services import attempts as attempt_service
from app.scenarios.library import builtin_scenarios
from app.scenarios.validator import validate_graph

# Fictional people; any resemblance to real employees is accidental. `synthetic` marks colleagues
# whose results are generated by the seed rather than played by a person.
DEMO_ACCOUNTS = [
    {"login": "provodnik", "full_name": "Алина Демидова", "depot": "Депо Восток", "brigade": "Бригада 1", "synthetic": False},
    {"login": "sergeev", "full_name": "Павел Сергеев", "depot": "Депо Восток", "brigade": "Бригада 1", "synthetic": True},
    {"login": "orlova", "full_name": "Ольга Орлова", "depot": "Депо Восток", "brigade": "Бригада 1", "synthetic": True},
    {"login": "kim", "full_name": "Дмитрий Ким", "depot": "Депо Восток", "brigade": "Бригада 2", "synthetic": True},
    {"login": "belova", "full_name": "Ирина Белова", "depot": "Депо Восток", "brigade": "Бригада 2", "synthetic": True},
    {"login": "nazarov", "full_name": "Тимур Назаров", "depot": "Депо Запад", "brigade": "Бригада 3", "synthetic": True},
    {"login": "metodist", "full_name": "Наталья Крылова", "depot": "Учебный центр", "brigade": "", "synthetic": False,
     "role": Role.methodologist.value},
]


# Pre-played paths for synthetic colleagues; None means "let the timer run out".
SYNTHETIC_RESULTS = {
    "sergeev": [("Место у окна", ["calm", "stow_together", "check", "tactful", "escort"]),
                ("Конфликт из-за откинутого кресла", ["c1"])],
    "orlova": [("Место у окна", ["order", "stow_together", "check", "tactful", "escort"]),
               ("Конфликт из-за откинутого кресла", ["c2"])],
    "kim": [("Место у окна", ["ignore", "call_senior"]), ("Конфликт из-за откинутого кресла", [None])],
    "belova": [("Место у окна", ["calm", "stow_yourself", "reseat_girl", "check_now", "tactful", "send_alone"])],
    "nazarov": [("Место у окна", ["calm", None, "call_colleague", "check", "tactful", "escort"]),
                ("Конфликт из-за откинутого кресла", ["c1"])],
}


def _play_synthetic(db: Session, employee: Employee, scenario: Scenario, path: list, start: datetime) -> None:
    view = attempt_service.start_attempt(db, employee.id, scenario.id, start)
    attempt_id = view.attempt.id
    db.get(Attempt, attempt_id).is_synthetic = True
    db.commit()
    now, state = start, view
    for choice in path:
        node = state.engine.current_node(state.attempt)
        now = now + timedelta(seconds=(node.get("timer_seconds") or 0) if choice is None else 7)
        state = attempt_service.submit_choice(db, attempt_id, employee.id, choice, state.attempt.step, now)


def seed_synthetic_results(db: Session, now: datetime) -> None:
    """Only for colleagues without any attempts, so re-running the seed adds nothing."""
    scenarios = {s.title: s for s in db.scalars(select(Scenario))}
    for day, (login, runs) in enumerate(SYNTHETIC_RESULTS.items(), start=1):
        employee = db.scalars(select(Employee).where(Employee.login == login)).first()
        if employee is None or db.scalar(select(func.count()).select_from(Attempt).where(Attempt.employee_id == employee.id)):
            continue
        for offset, (title, path) in enumerate(runs):
            if title in scenarios:
                _play_synthetic(db, employee, scenarios[title], path, now - timedelta(days=day, hours=offset))


def seed_accounts(db: Session, password: str) -> None:
    for spec in DEMO_ACCOUNTS:
        employee = db.query(Employee).filter_by(login=spec["login"]).first()
        if employee is None:
            employee = Employee(login=spec["login"])
            db.add(employee)
        employee.full_name = spec["full_name"]
        employee.depot = spec["depot"]
        employee.brigade = spec["brigade"]
        employee.role = spec.get("role", Role.conductor.value)
        employee.is_synthetic = spec["synthetic"]
        # Re-hash only when the configured password changed, so repeated seeds are no-ops.
        if not verify_password(password, employee.password_hash):
            employee.password_hash = hash_password(password)


def seed(db: Session) -> None:
    scenarios = builtin_scenarios()
    for data in scenarios:
        validate_graph(data["graph"])

    for data in scenarios:
        existing = db.query(Scenario).filter_by(title=data["title"]).first()
        tags = data.get("tags", [])
        if existing is None:
            db.add(Scenario(title=data["title"], description=data["description"], tags=tags, graph=data["graph"]))
        elif existing.graph != data["graph"] or existing.description != data["description"] or existing.tags != tags:
            existing.graph = data["graph"]
            existing.description = data["description"]
            existing.tags = tags
            existing.version += 1

    seed_accounts(db, settings.demo_password)
    db.commit()
    seed_synthetic_results(db, utcnow())


def run() -> None:
    with SessionLocal() as db:
        seed(db)
    print("Seed complete.")


if __name__ == "__main__":
    run()
