"""Load built-in scenarios and fictional demo accounts.

Run after migrations: python -m app.db_upgrade && python -m app.seed
A scenario whose data changed is updated in place with version + 1; attempts
already started keep their own snapshot.
"""

from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.db import SessionLocal
from app.core.security import hash_password, verify_password
from app.models.models import Employee, Role, Scenario
from app.scenarios.library import builtin_scenarios
from app.scenarios.validator import validate_graph

# Fictional people; any resemblance to real employees is accidental. `synthetic` marks colleagues
# whose results are generated by the seed rather than played by a person.
DEMO_ACCOUNTS = [
    {"login": "provodnik", "full_name": "Алина Демидова", "depot": "Депо Восток", "brigade": "Бригада 1", "synthetic": False},
    {"login": "sergeev", "full_name": "Павел Сергеев", "depot": "Депо Восток", "brigade": "Бригада 1", "synthetic": True},
    {"login": "orlova", "full_name": "Ольга Орлова", "depot": "Депо Восток", "brigade": "Бригада 1", "synthetic": True},
    {"login": "kim", "full_name": "Дмитрий Ким", "depot": "Депо Восток", "brigade": "Бригада 2", "synthetic": True},
    {"login": "belova", "full_name": "Ирина Белова", "depot": "Депо Восток", "brigade": "Бригада 2", "synthetic": True},
    {"login": "nazarov", "full_name": "Тимур Назаров", "depot": "Депо Запад", "brigade": "Бригада 3", "synthetic": True},
    {"login": "metodist", "full_name": "Наталья Крылова", "depot": "Учебный центр", "brigade": "", "synthetic": False,
     "role": Role.methodologist.value},
]


def seed_accounts(db: Session, password: str) -> None:
    for spec in DEMO_ACCOUNTS:
        employee = db.query(Employee).filter_by(login=spec["login"]).first()
        if employee is None:
            employee = Employee(login=spec["login"])
            db.add(employee)
        employee.full_name = spec["full_name"]
        employee.depot = spec["depot"]
        employee.brigade = spec["brigade"]
        employee.role = spec.get("role", Role.conductor.value)
        employee.is_synthetic = spec["synthetic"]
        # Re-hash only when the configured password changed, so repeated seeds are no-ops.
        if not verify_password(password, employee.password_hash):
            employee.password_hash = hash_password(password)


def seed(db: Session) -> None:
    scenarios = builtin_scenarios()
    for data in scenarios:
        validate_graph(data["graph"])

    for data in scenarios:
        existing = db.query(Scenario).filter_by(title=data["title"]).first()
        if existing is None:
            db.add(Scenario(title=data["title"], description=data["description"], graph=data["graph"]))
        elif existing.graph != data["graph"] or existing.description != data["description"]:
            existing.graph = data["graph"]
            existing.description = data["description"]
            existing.version += 1

    seed_accounts(db, settings.demo_password)
    db.commit()


def run() -> None:
    with SessionLocal() as db:
        seed(db)
    print("Seed complete.")


if __name__ == "__main__":
    run()
